import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>


        <nav className={styles.navbar}>
            <div className={styles.logo}>
                    <img src='https://firebasestorage.googleapis.com/v0/b/prayut-rxltjj.appspot.com/o/Group.png?alt=media&token=19e2cb56-3fd5-4ba9-a9b2-8cafa5654366'>
                    </img>
            </div>
            <div className={styles.sectiontop}>
                <p>MAKETPLACE_</p>
                    <img src='https://firebasestorage.googleapis.com/v0/b/prayut-rxltjj.appspot.com/o/Back.png?alt=media&token=22386e45-13e1-40a4-aaa0-ec97c5fd1ee8'>
                    </img>
                <button>BACK</button>
            </div>

            <div className={styles.sectionbottom}>
                <a>NAKA MARKET</a>
                <a>P2P MARKET</a>
                <a>NAKAVERSE MAP</a>
            </div>
        </nav>

        <div className={styles.sectionCanter}>
            <div className={styles.cardSingin}>
                <h2>Sing in</h2>
                <input type="text" placeholder="Email address" />
                <input type="text" placeholder="Password" />
                <button className={styles.btnSignin} type='button'>SIGN IN</button>
                <a >Forgot Password</a>
                <button className={styles.btnRegister} type='button'>SIGN IN</button>
                <p>Hanc ego assentior cum a philosophis compluribus 
                  permulta dicantur.
                </p>
            </div>
        </div>



    </div>
  )
}
